### ISSUE TITLE
this sucks

### ISSUE THREAD

**Issue by Brambleboy** [Lolson31/hello#1]
maybe learn to code next time rirnhead
try this: `jump_off(bridge);`

**Comment by Lolson31** [comment]
:)

**Comment by Lolson31** [comment]
Sale.frown();
[cid:d3f47492-50b0-40c4-bcbe-55ae9d806dd0]
________________________________
From: Brambleboy ***@***.***>
Sent: Friday, February 19, 2021 6:31 PM
To: Lolson31/hello ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Lolson31/hello] this sucks (#1)

Non-NU Email
________________________________

maybe learn to code next time rirnhead
try this: jump_off(bridge);
